In [1]:
import cv2
import numpy as np
import os

# Chemins vers les dossiers de données d'entraînement et de test
train_data_folder = "D:/UQAC ETE 2023/8INF867_Fondamentaux de l'apprentissage automatique/Projet/FAA_Project/FAA_project/data/train_10000/train_10000"  # Mettez le bon chemin vers votre dossier de train
test_data_folder = "D:/UQAC ETE 2023/8INF867_Fondamentaux de l'apprentissage automatique/Projet/FAA_Project/FAA_project/data/data"  # Mettre le bon chemin
emotions = ["anger", "disgust", "fear", "happiness", "neutral", "sadness", "surprise"]

# Prétraitement des données
def preprocess_data(data_directory):
    images = []
    labels = []

    for emotion in emotions:
        emotion_path = os.path.join(data_directory, emotion)
        for image_name in os.listdir(emotion_path):
            image_path = os.path.join(emotion_path, image_name)
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Charger l'image en niveaux de gris
            image = cv2.resize(image, (48, 48))  # Redimensionner l'image
            images.append(image)
            labels.append(emotions.index(emotion))  # Étiqueter l'image avec l'indice de l'émotion

    return np.array(images), np.array(labels)

# Chargement des données d'entraînement
train_images, train_labels = preprocess_data(train_data_folder)

# Chargement des données de test
test_images, test_labels = preprocess_data(test_data_folder)

In [2]:
# Reduce the samples to train
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Determine the desired sample size
sample_size = 8000

# Convert train_images to a NumPy array
train_images_array = np.array(train_images)
print(train_images_array.shape)

# Reshape train_images_array into a 2D array
n_samples = train_images_array.shape[0]
train_images_2d = train_images_array.reshape((n_samples, -1))

# Convert train_images_2d to DataFrame
train_data_df = pd.DataFrame(train_images_2d, columns=[f'feature_{i}' for i in range(train_images_2d.shape[1])])

# Perform random sampling while maintaining the same proportion for each class
X_train_df, _, y_train, _ = train_test_split(train_data_df, train_labels, train_size=sample_size, stratify=train_labels, random_state=42)

# Extract the feature data as a 2D array
X_train = X_train_df.values

print(X_train.shape)

(69802, 48, 48)
(8000, 2304)


In [3]:
# Reducing the test set
# Determine the desired sample size
sample_size = 2000

# Convert test_images to a NumPy array
test_images_array = np.array(test_images)

# Reshape test_images_array into a 2D array
n_samples = test_images_array.shape[0]
test_images_2d = test_images_array.reshape((n_samples, -1))

# Convert test_images_2d to DataFrame
test_data_df = pd.DataFrame(test_images_2d, columns=[f'feature_{i}' for i in range(test_images_2d.shape[1])])

# Perform random sampling while maintaining the same proportion for each class
X_test_df, _, y_test, _ = train_test_split(test_data_df, test_labels, train_size=sample_size, stratify=test_labels, random_state=42)

# Extract the feature data as a 2D array
X_test = X_test_df.values

print(X_test.shape)

(2000, 2304)


In [4]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, cohen_kappa_score

from sklearn.svm import SVC

# #############################################################################
# Split into a training set and a validation set using a stratified k fold

# Define the number of folds
k = 5

# Initialize the stratified k-fold object
skf = StratifiedKFold(n_splits=k, random_state=42, shuffle=True)

# Lists to store the training and validation sets
train_indices = []
val_indices = []

# Perform stratified k-fold splitting
for train_index, val_index in skf.split(X_train, y_train):
    train_indices.append(train_index)
    val_indices.append(val_index)
    modified_val_index= val_index
    val_indices.append(modified_val_index)

In [5]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Access the data for each fold
for fold in range(k):
    train_data= np.array(X_train)[train_indices[fold]]
    train_labels_fold = np.array(y_train)[train_indices[fold]]
    X_val = np.array(X_train)[val_indices[fold]]
    val_labels_fold = np.array(y_train)[val_indices[fold]]
    print("Fold: ",fold, "X_train shape: ", train_data.shape, "y_train shape: ", train_labels_fold.shape, "X_val shape: ", X_val.shape, "y_val shape: ", val_labels_fold.shape)

    # Reshape images into a 2D array
    X_train_2d = train_data.reshape((train_data.shape[0], -1))
    X_val_2d = X_val.reshape((X_val.shape[0], -1))
    X_test_2d = X_test.reshape((X_test.shape[0], -1))

    #Scale the data
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_2d)
    X_val_scaled = scaler.transform(X_val_2d)
    X_test_scaled = scaler.transform(X_test_2d)

    # Compute PCA on the training and validation set
    n_components = 60  # Specify the desired number of components
    pca = PCA(n_components=n_components, svd_solver='randomized', whiten=True)
    X_train_pca = pca.fit_transform(X_train_2d)
    X_val_pca = pca.transform(X_val_2d)
    X_test_pca = pca.transform(X_test_2d)

    # Verify the shape of PCA-transformed images
    print("Shape of train images after PCA: ", X_train_pca.shape)
    print("Shape of validation images after PCA: ", X_val_pca.shape)
    print("Shape of test images after PCA: ", X_test_pca.shape)


Fold:  0 X_train shape:  (6400, 2304) y_train shape:  (6400,) X_val shape:  (1600, 2304) y_val shape:  (1600,)
Shape of train images after PCA:  (6400, 60)
Shape of validation images after PCA:  (1600, 60)
Shape of test images after PCA:  (2000, 60)
Fold:  1 X_train shape:  (6400, 2304) y_train shape:  (6400,) X_val shape:  (1600, 2304) y_val shape:  (1600,)
Shape of train images after PCA:  (6400, 60)
Shape of validation images after PCA:  (1600, 60)
Shape of test images after PCA:  (2000, 60)
Fold:  2 X_train shape:  (6400, 2304) y_train shape:  (6400,) X_val shape:  (1600, 2304) y_val shape:  (1600,)
Shape of train images after PCA:  (6400, 60)
Shape of validation images after PCA:  (1600, 60)
Shape of test images after PCA:  (2000, 60)
Fold:  3 X_train shape:  (6400, 2304) y_train shape:  (6400,) X_val shape:  (1600, 2304) y_val shape:  (1600,)
Shape of train images after PCA:  (6400, 60)
Shape of validation images after PCA:  (1600, 60)
Shape of test images after PCA:  (2000, 60)


In [ ]:
from sklearn.model_selection import GridSearchCV
# Train a SVM classification model
# Define the parameter grid for grid search
param_grid = {'C': [0.01, 0.1, 1, 10, 100, 1000],
              'gamma': [0.001, 0.01, 0.1, 1, 10, 100]}

# Initialize the SVM classifier
svm = SVC(kernel='rbf', class_weight='balanced')

# Perform grid search to find the best hyperparameters
optimal_params = GridSearchCV(svm, param_grid)
optimal_params.fit(X_train_pca, train_labels_fold)
# Print the best estimator found by grid search
print("Best hyperparameters found by grid search:")
print(optimal_params.best_params_)
print("Best estimator:")
print(optimal_params.best_estimator_)

In [25]:
#Computing the SVM model with the best parameters obtained
from sklearn.metrics import accuracy_score
# List to save the model performance for each fold
accuracy_scores = []
# SVM model training on each fold
for fold in range(k):
    # Creation, training and evaluation for the current fold
    clf_svm = SVC(C= 10,kernel="rbf",gamma = 0.01, class_weight = 'balanced')
    clf_svm.fit(X_train_pca,train_labels_fold)

    y_pred_fold = clf_svm.predict(X_val_pca)
    accuracy = accuracy_score(val_labels_fold, y_pred_fold)
    accuracy_scores.append(accuracy)

    # Accuracy score for the current fold
    print("Fold:", fold+1, "Accuracy:", accuracy)

    # Evaluate the model for the current fold
    print("Classification Report:")
    print(classification_report(val_labels_fold, y_pred_fold))

    # Print confusion matrix for the current fold
    print("Confusion Matrix:")
    print(confusion_matrix(val_labels_fold, y_pred_fold))

    # Print Cohen's Kappa score for the current fold
    print("Cohen's Kappa score: ", cohen_kappa_score(val_labels_fold, y_pred_fold))
# Mean accuracy for all the folds
mean_accuracy = np.mean(accuracy_scores)
print("Mean Accuracy:", mean_accuracy)

Fold: 1 Accuracy: 0.951875
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.93      0.95       229
           1       0.96      0.97      0.96       225
           2       0.97      0.93      0.95       229
           3       0.93      0.97      0.95       230
           4       0.91      0.97      0.94       229
           5       0.95      0.94      0.95       229
           6       0.96      0.96      0.96       229

    accuracy                           0.95      1600
   macro avg       0.95      0.95      0.95      1600
weighted avg       0.95      0.95      0.95      1600

Confusion Matrix:
[[212   5   1   3   4   4   0]
 [  0 219   1   3   1   1   0]
 [  2   3 212   3   7   1   1]
 [  0   0   0 224   2   2   2]
 [  0   1   1   3 222   0   2]
 [  1   1   2   0   7 215   3]
 [  0   0   2   4   1   3 219]]
Cohen's Kappa score:  0.9438539181032832
Fold: 2 Accuracy: 0.951875
Classification Report:
              precision   

In [26]:
import pickle
# Save the model object
model_svm = 'svm_model_1.pkl'
with open(model_svm, 'wb') as file:
    pickle.dump(clf_svm, file)

In [27]:
# Load the saved model
model_svm = 'svm_model_1.pkl'
with open(model_svm, 'rb') as file:
    loaded_svm = pickle.load(file)

In [28]:
from time import time
# Evaluating on the test set

print("Predicting on the test set")
t0 = time()
y_pred = loaded_svm.predict(X_test_pca)
print("done in %0.3fs" % (time() - t0))

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Print Cohen's Kappa score
print("Cohen's Kappa score: ", cohen_kappa_score(y_test, y_pred))

Predicting on the test set
done in 1.180s
Classification Report:
              precision    recall  f1-score   support

           0       0.29      0.30      0.29       286
           1       0.47      0.52      0.50       286
           2       0.26      0.24      0.25       286
           3       0.46      0.47      0.46       285
           4       0.29      0.34      0.31       286
           5       0.31      0.24      0.27       286
           6       0.63      0.59      0.61       285

    accuracy                           0.39      2000
   macro avg       0.39      0.39      0.39      2000
weighted avg       0.39      0.39      0.39      2000

Confusion Matrix:
[[ 86  32  35  30  51  37  15]
 [ 29 150  27  12  40  20   8]
 [ 55  44  70  38  32  25  22]
 [ 27  24  23 133  36  26  16]
 [ 36  26  26  37  96  40  25]
 [ 50  30  52  20  50  70  14]
 [ 15  10  38  20  24   9 169]]
Cohen's Kappa score:  0.2848307408447689


In [ ]:
# Predict on 1 image
print("Predicting on 1 image")

t0 = time()
y_pred = loaded_svm.predict(X_test_pca)
print("done in %0.3fs" % (time() - t0))

# Print classification report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Print Cohen's Kappa score
print("Cohen's Kappa score: ", cohen_kappa_score(y_test, y_pred))

In [29]:
# Saving the metrics of the model in a dictionary
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pickle

def save_element(x, name="element", binary=True, ext=".pkl"):
    if binary:
        mode = 'wb'
        encod='_bin'
    else:
        encod=""
        mode = 'w'
    file = open(name +encod + ext, mode)
    pickle.dump(x, file)
    file.close()
    print("File "+name+" saved")

hist = {
    'test_accuracy': accuracy_score(y_test, y_pred),
    'test_report': classification_report(y_test, y_pred, output_dict=False, target_names=emotions),
    'test_report_dict': classification_report(y_test, y_pred, output_dict=True, target_names=emotions),
    'test_cf_matrix': confusion_matrix(y_test, y_pred),
    'test_kappa': cohen_kappa_score(y_test, y_pred)}

save_element(hist, "history_dict_svm1")

File history_dict_svm1 saved
